import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { CalendarDays, Megaphone, Pencil, Pin, Plus, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { useAuth } from "@/lib/auth-context";
import { muralDb, muralTipoLabel, todayISO, type MuralPublicacao, type MuralTipo } from "@/lib/mural";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { Textarea } from "@/components/ui/textarea";

export const Route = createFileRoute("/mural")({ component: MuralAdminPage });

const formInicial = () => ({ titulo: "", conteudo: "", tipo: "aviso" as MuralTipo, data_evento: "", hora_evento: "", inicio_exibicao: todayISO(), fim_exibicao: "", fixado: false, ativo: true });

function MuralAdminPage() {
  const { isAdmin, user } = useAuth();
  const qc = useQueryClient();
  const [editando, setEditando] = useState<MuralPublicacao | null>(null);
  const [aberto, setAberto] = useState(false);
  const { data: publicacoes = [], isLoading } = useQuery({ queryKey: ["mural_publicacoes", "admin"], enabled: isAdmin, queryFn: async () => { const { data, error } = await muralDb.from("mural_publicacoes").select("*").order("ativo", { ascending: false }).order("fixado", { ascending: false }).order("created_at", { ascending: false }); if (error) throw error; return (data ?? []) as MuralPublicacao[]; } });
  const excluir = useMutation({ mutationFn: async (id: string) => { const { error } = await muralDb.from("mural_publicacoes").delete().eq("id", id); if (error) throw error; }, onSuccess: () => { toast.success("Publicação excluída."); qc.invalidateQueries({ queryKey: ["mural_publicacoes"] }); }, onError: (e: Error) => toast.error(e.message) });
  if (!isAdmin) return <div className="p-4 sm:p-6 lg:p-8"><Card className="p-6"><h1 className="text-lg font-semibold">Acesso restrito</h1><p className="mt-1 text-sm text-muted-foreground">Somente administradores podem gerenciar o mural.</p></Card></div>;
  const abrirNovo = () => { setEditando(null); setAberto(true); };
  const abrirEdicao = (publicacao: MuralPublicacao) => { setEditando(publicacao); setAberto(true); };
  return <div className="p-4 sm:p-6 lg:p-8 space-y-6"><header className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-2xl font-semibold">Gerenciar mural</h1><p className="mt-1 text-sm text-muted-foreground">Publique avisos, destaques e eventos para a comunidade escolar.</p></div><Button onClick={abrirNovo}><Plus className="h-4 w-4" />Nova publicação</Button></header><div className="grid gap-4 lg:grid-cols-2">{isLoading && <p className="text-sm text-muted-foreground">Carregando...</p>}{!isLoading && publicacoes.length === 0 && <Card className="border-dashed p-10 text-center text-sm text-muted-foreground lg:col-span-2">Nenhuma publicação cadastrada.</Card>}{publicacoes.map((item) => <Card key={item.id} className={!item.ativo ? "opacity-60" : ""}><CardHeader className="pb-3"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-medium uppercase tracking-wide text-primary">{muralTipoLabel[item.tipo]}{item.fixado && " · Fixado"}</p><CardTitle className="mt-1 text-lg">{item.titulo}</CardTitle></div><div className="flex gap-1"><Button variant="ghost" size="icon" title="Editar" onClick={() => abrirEdicao(item)}><Pencil className="h-4 w-4" /></Button><Button variant="ghost" size="icon" title="Excluir" onClick={() => confirm(`Excluir “${item.titulo}”?`) && excluir.mutate(item.id)}><Trash2 className="h-4 w-4 text-destructive" /></Button></div></div></CardHeader><CardContent><p className="line-clamp-3 whitespace-pre-wrap text-sm text-muted-foreground">{item.conteudo}</p><div className="mt-4 flex flex-wrap gap-2 text-xs text-muted-foreground"><span>{item.ativo ? "Ativo" : "Arquivado"}</span><span>Exibe de {new Date(`${item.inicio_exibicao}T00:00:00`).toLocaleDateString("pt-BR")}{item.fim_exibicao ? ` até ${new Date(`${item.fim_exibicao}T00:00:00`).toLocaleDateString("pt-BR")}` : ""}</span>{item.data_evento && <span>Evento: {new Date(`${item.data_evento}T00:00:00`).toLocaleDateString("pt-BR")}</span>}</div></CardContent></Card>)}</div><PublicacaoDialog open={aberto} onClose={() => setAberto(false)} editando={editando} criadoPor={user?.id ?? null} /></div>;
}

function PublicacaoDialog({ open, onClose, editando, criadoPor }: { open: boolean; onClose: () => void; editando: MuralPublicacao | null; criadoPor: string | null }) {
  const qc = useQueryClient();
  const [form, setForm] = useState(() => formInicial());
  useEffect(() => {
    if (!open) return;
    setForm(editando ? { titulo: editando.titulo, conteudo: editando.conteudo, tipo: editando.tipo, data_evento: editando.data_evento ?? "", hora_evento: editando.hora_evento?.slice(0, 5) ?? "", inicio_exibicao: editando.inicio_exibicao, fim_exibicao: editando.fim_exibicao ?? "", fixado: editando.fixado, ativo: editando.ativo } : formInicial());
  }, [editando, open]);
  const alterar = <K extends keyof typeof form>(campo: K, valor: (typeof form)[K]) => setForm((atual) => ({ ...atual, [campo]: valor }));
  const salvar = useMutation({ mutationFn: async () => { if (!form.titulo.trim() || !form.conteudo.trim()) throw new Error("Informe título e conteúdo."); if (form.tipo === "evento" && !form.data_evento) throw new Error("Informe a data do evento."); const payload = { titulo: form.titulo.trim(), conteudo: form.conteudo.trim(), tipo: form.tipo, data_evento: form.data_evento || null, hora_evento: form.hora_evento || null, inicio_exibicao: form.inicio_exibicao, fim_exibicao: form.fim_exibicao || null, fixado: form.fixado, ativo: form.ativo }; const result = editando ? await muralDb.from("mural_publicacoes").update(payload).eq("id", editando.id) : await muralDb.from("mural_publicacoes").insert({ ...payload, criado_por: criadoPor }); if (result.error) throw result.error; }, onSuccess: () => { toast.success(editando ? "Publicação atualizada." : "Publicação criada."); qc.invalidateQueries({ queryKey: ["mural_publicacoes"] }); setForm(formInicial()); onClose(); }, onError: (e: Error) => toast.error(e.message) });
  return <Dialog open={open} onOpenChange={(value) => !value && onClose()}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-xl"><DialogHeader><DialogTitle>{editando ? "Editar publicação" : "Nova publicação"}</DialogTitle></DialogHeader><div className="space-y-4 py-2"><div className="space-y-2"><Label>Título</Label><Input value={form.titulo} onChange={(e) => alterar("titulo", e.target.value)} /></div><div className="space-y-2"><Label>Conteúdo</Label><Textarea rows={5} value={form.conteudo} onChange={(e) => alterar("conteudo", e.target.value)} /></div><div className="grid gap-3 sm:grid-cols-2"><div className="space-y-2"><Label>Tipo</Label><Select value={form.tipo} onValueChange={(value) => alterar("tipo", value as MuralTipo)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="aviso">Aviso</SelectItem><SelectItem value="destaque">Destaque</SelectItem><SelectItem value="evento">Evento</SelectItem></SelectContent></Select></div><div className="space-y-2"><Label>Início da exibição</Label><Input type="date" value={form.inicio_exibicao} onChange={(e) => alterar("inicio_exibicao", e.target.value)} /></div></div>{form.tipo === "evento" && <div className="grid gap-3 sm:grid-cols-2"><div className="space-y-2"><Label>Data do evento</Label><Input type="date" value={form.data_evento} onChange={(e) => alterar("data_evento", e.target.value)} /></div><div className="space-y-2"><Label>Horário (opcional)</Label><Input type="time" value={form.hora_evento} onChange={(e) => alterar("hora_evento", e.target.value)} /></div></div>}<div className="space-y-2"><Label>Fim da exibição (opcional)</Label><Input type="date" value={form.fim_exibicao} onChange={(e) => alterar("fim_exibicao", e.target.value)} /></div><div className="grid gap-3 sm:grid-cols-2"><label className="flex items-center gap-3 rounded-md border p-3 text-sm"><Switch checked={form.fixado} onCheckedChange={(value) => alterar("fixado", value)} /><span><Pin className="mr-1 inline h-3.5 w-3.5" />Fixar no mural</span></label><label className="flex items-center gap-3 rounded-md border p-3 text-sm"><Switch checked={form.ativo} onCheckedChange={(value) => alterar("ativo", value)} />Publicação ativa</label></div></div><DialogFooter><Button variant="outline" onClick={onClose}>Cancelar</Button><Button onClick={() => salvar.mutate()} disabled={salvar.isPending}>{salvar.isPending ? "Salvando..." : "Salvar publicação"}</Button></DialogFooter></DialogContent></Dialog>;
}
