/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as TurmasRouteImport } from './routes/turmas'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HorariosRouteImport } from './routes/horarios'
import { Route as DocentesRouteImport } from './routes/docentes'
import { Route as ComponentesRouteImport } from './routes/componentes'
import { Route as AlterarSenhaRouteImport } from './routes/alterar-senha'
import { Route as AgendamentoRouteImport } from './routes/agendamento'
import { Route as IndexRouteImport } from './routes/index'

const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const TurmasRoute = TurmasRouteImport.update({
  id: '/turmas',
  path: '/turmas',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HorariosRoute = HorariosRouteImport.update({
  id: '/horarios',
  path: '/horarios',
  getParentRoute: () => rootRouteImport,
} as any)
const DocentesRoute = DocentesRouteImport.update({
  id: '/docentes',
  path: '/docentes',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentesRoute = ComponentesRouteImport.update({
  id: '/componentes',
  path: '/componentes',
  getParentRoute: () => rootRouteImport,
} as any)
const AlterarSenhaRoute = AlterarSenhaRouteImport.update({
  id: '/alterar-senha',
  path: '/alterar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendamentoRoute = AgendamentoRouteImport.update({
  id: '/agendamento',
  path: '/agendamento',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agendamento': typeof AgendamentoRoute
  '/alterar-senha': typeof AlterarSenhaRoute
  '/componentes': typeof ComponentesRoute
  '/docentes': typeof DocentesRoute
  '/horarios': typeof HorariosRoute
  '/login': typeof LoginRoute
  '/relatorios': typeof RelatoriosRoute
  '/turmas': typeof TurmasRoute
  '/usuarios': typeof UsuariosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agendamento': typeof AgendamentoRoute
  '/alterar-senha': typeof AlterarSenhaRoute
  '/componentes': typeof ComponentesRoute
  '/docentes': typeof DocentesRoute
  '/horarios': typeof HorariosRoute
  '/login': typeof LoginRoute
  '/relatorios': typeof RelatoriosRoute
  '/turmas': typeof TurmasRoute
  '/usuarios': typeof UsuariosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agendamento': typeof AgendamentoRoute
  '/alterar-senha': typeof AlterarSenhaRoute
  '/componentes': typeof ComponentesRoute
  '/docentes': typeof DocentesRoute
  '/horarios': typeof HorariosRoute
  '/login': typeof LoginRoute
  '/relatorios': typeof RelatoriosRoute
  '/turmas': typeof TurmasRoute
  '/usuarios': typeof UsuariosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agendamento'
    | '/alterar-senha'
    | '/componentes'
    | '/docentes'
    | '/horarios'
    | '/login'
    | '/relatorios'
    | '/turmas'
    | '/usuarios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agendamento'
    | '/alterar-senha'
    | '/componentes'
    | '/docentes'
    | '/horarios'
    | '/login'
    | '/relatorios'
    | '/turmas'
    | '/usuarios'
  id:
    | '__root__'
    | '/'
    | '/agendamento'
    | '/alterar-senha'
    | '/componentes'
    | '/docentes'
    | '/horarios'
    | '/login'
    | '/relatorios'
    | '/turmas'
    | '/usuarios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendamentoRoute: typeof AgendamentoRoute
  AlterarSenhaRoute: typeof AlterarSenhaRoute
  ComponentesRoute: typeof ComponentesRoute
  DocentesRoute: typeof DocentesRoute
  HorariosRoute: typeof HorariosRoute
  LoginRoute: typeof LoginRoute
  RelatoriosRoute: typeof RelatoriosRoute
  TurmasRoute: typeof TurmasRoute
  UsuariosRoute: typeof UsuariosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/turmas': {
      id: '/turmas'
      path: '/turmas'
      fullPath: '/turmas'
      preLoaderRoute: typeof TurmasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horarios': {
      id: '/horarios'
      path: '/horarios'
      fullPath: '/horarios'
      preLoaderRoute: typeof HorariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docentes': {
      id: '/docentes'
      path: '/docentes'
      fullPath: '/docentes'
      preLoaderRoute: typeof DocentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/componentes': {
      id: '/componentes'
      path: '/componentes'
      fullPath: '/componentes'
      preLoaderRoute: typeof ComponentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alterar-senha': {
      id: '/alterar-senha'
      path: '/alterar-senha'
      fullPath: '/alterar-senha'
      preLoaderRoute: typeof AlterarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendamento': {
      id: '/agendamento'
      path: '/agendamento'
      fullPath: '/agendamento'
      preLoaderRoute: typeof AgendamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendamentoRoute: AgendamentoRoute,
  AlterarSenhaRoute: AlterarSenhaRoute,
  ComponentesRoute: ComponentesRoute,
  DocentesRoute: DocentesRoute,
  HorariosRoute: HorariosRoute,
  LoginRoute: LoginRoute,
  RelatoriosRoute: RelatoriosRoute,
  TurmasRoute: TurmasRoute,
  UsuariosRoute: UsuariosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
